# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  dotnet: rocketinsights/dotnet@0.0.1

workflows:
  default:
    jobs:
      - dotnet\build-test-pack-push:
          context: team-dotnet