# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  test:
    description: Setup and run application tests
    working_directory: ~/project
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Information"
          command: pwd
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "./src/RocketInsights.sln" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore ./src/RocketInsights.sln
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "./src/RocketInsights.sln" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test ./src/RocketInsights.sln -v n --results-directory:test_coverage --collect:"XPlat Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\src\test_coverage
  build:
    description: Build application with Release configuration
    working_directory: ~/project
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe ./src/RocketInsights.sln build --configuration Release

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test